export const videosData = [
    {
        id: 1,
        url: 'https://www.youtube.com/watch?v=cF2lQ_gZeA8&list=PLC3y8-rFHvwisvxhZ135pogtX7_Oe3Q3A&index=2&t=0s',
        title: 'React Hooks Tutorial - 1 - Introduction',
        comments: [],
        vues: 0,
    },
    {
        id: 2,
        url: 'https://www.youtube.com/watch?v=lAW1Jmmr9hc&list=PLC3y8-rFHvwisvxhZ135pogtX7_Oe3Q3A&index=3&t=0s',
        title: 'React Hooks Tutorial - 2 - useState Hook',
        comments: [],
        vues: 0,
    },
    {
        id: 3,
        url: 'https://www.youtube.com/watch?v=d0plTCQgsXs&list=PLC3y8-rFHvwisvxhZ135pogtX7_Oe3Q3A&index=4&t=0s',
        title: 'React Hooks Tutorial - 3 - useState with previous state',
        comments: [],
        vues: 0,
    },
    {
        id: 4,
        url: 'https://www.youtube.com/watch?v=-3lL8oyev9w&list=PLC3y8-rFHvwisvxhZ135pogtX7_Oe3Q3A&index=5&t=0s',
        title: 'React Hooks Tutorial - 4 - useState with object',
        comments: [],
        vues: 0,
    },
    {
        id: 5,
        url: 'https://www.youtube.com/watch?v=RZ5wKYbOM_I&list=PLC3y8-rFHvwisvxhZ135pogtX7_Oe3Q3A&index=6&t=176s',
        title: 'React Hooks Tutorial - 5 - useState with array',
        comments: [],
        vues: 0,
    },
    {
        id: 6,
        url: 'https://www.youtube.com/watch?v=06Y6aJzTmXY&list=PLC3y8-rFHvwisvxhZ135pogtX7_Oe3Q3A&index=7&t=0s',
        title: 'React Hooks Tutorial - 6 - useEffect Hook',
        comments: [],
        vues: 0,
    },
    {
        id: 7,
        url: 'https://www.youtube.com/watch?v=nAuWOnFMlOw&list=PLC3y8-rFHvwisvxhZ135pogtX7_Oe3Q3A&index=8&t=0s',
        title: 'React Hooks Tutorial - 7 - useEffect after render',
        comments: [],
        vues: 0,
    },
    {
        id: 8,
        url: 'https://www.youtube.com/watch?v=8DYlzVUTC7s&list=PLC3y8-rFHvwisvxhZ135pogtX7_Oe3Q3A&index=8',
        title: 'React Hooks Tutorial - 8 - Conditionally run effects',
        comments: [],
        vues: 0,
    },
    {
        id: 9,
        url: 'https://www.youtube.com/watch?v=ejN-oAw9vC0',
        title: '3: Get data from a database without refreshing the browser using AJAX - Learn AJAX programming',
        comments: [],
        vues: 0,
    },
    {
        id: 10,
        url: 'https://www.youtube.com/watch?v=XRFMSdgnKPE',
        title: 'Installing ESLint for React and React Native development',
        comments: [],
        vues: 0,
    },
    {
        id: 11,
        url: 'https://www.youtube.com/watch?v=GLSG_Wh_YWc',
        title: 'Flutter Tutorial for Beginners - Build iOS and Android Apps with Google\'s Flutter & Dart',
        comments: [],
        vues: 0,
    },
    {
        id: 12,
        url: 'https://www.youtube.com/watch?v=lYWYWyX04JI',
        title: 'Angular vs React vs Vue [2020 Update]',
        comments: [],
        vues: 0,
    },

];